### ISSUE TITLE
CUDA out of Memory

### ISSUE THREAD

**Issue by lisa676** [zju3dv/mvpose#41]
Hi @DongJT1996 as I already commented my problem in this issue #31  and you suggested to check the CPN because problem was due to 2D detector. 

1: CPN is using ResNet50 and Resnet101 with 256x192 and 384x288. So I run original CPN by using both combinations (RestNet50 and 101 with both inputs) so there is no any problem in CPN.
2: In MV-Pose you used ResNet101.384x288 in 2D detection, I changed it to ResNet50.256x192 to solve the memory issue but again same problem. Still I'm facing "CUDA out of memory" problem. 

It seems that there is no problem in CPN part, may be there is problem in 3D part which is using higher memory. Can you check it and suggest some changes so that we can use this project even lower GPU memory (6GB). 

If I change the batch size in 2D detector as I mentioned in #31 I got "List index out of range" error.

**Comment by JiangWenPL** [comment]
I would suggest you to dump the results for 2D detectors if you still have this problem. The 2D detection/ pose estimation are decoupled from our method. The following links might be helpful if you want to save the 2D results first.
[Here](https://github.com/zju3dv/mvpose/blob/2e61d2845e5d2c9b80ae12be09b8c4b201761df7/src/m_utils/evaluate.py#L62), [here](https://github.com/zju3dv/mvpose/blob/2e61d2845e5d2c9b80ae12be09b8c4b201761df7/src/models/estimate3d.py#L40) and [here](https://github.com/zju3dv/mvpose/blob/master/src/tools/preprocess.py)

**Comment by cbiras** [comment]
Hi @lan786 , did you solve this problem somehow? I also tried to change the batch_size in the 2D detector, but got the List index out of range error.

**Comment by lan786** [comment]
Hi @cbiras  I gave my best try but unable to solve the problem. I moved to 11GB GPU then problem is gone. 

If you solve this problem then kindly share so that it will be helpful for all of us in future.

**Comment by cbiras** [comment]
Unfortunately my GPU has only 3GB so I had to improvise, and moved everything on Google Colab, and it's working fine now.

**Comment by AntonioEscamilla** [comment]
Hi, @lisa676 and @cbiras!!
I can see from your comments that you manage to run mvpose using the CPN backbone for 2d pose estimation.
I am trying to use a different 2d pose estimator since I couldn't compile the default backbones (Light RCNN + CPN).
Can you look in your implementations to check the dimensions of the dumped results from the Detector2D object?
In particular, I am struggling to fit my results to these variables: 
https://github.com/zju3dv/mvpose/blob/38b958f423f2de2bf7562f5a386c27440eab8c53/backend/tf_cpn/Detector2D.py#L217-L220
* cls_skeleton[i][:-1] => size[17,2] or size[17,3] ??
* heatmaps[I] => size[17, img_lght, img_width] ??
* crops[I] => size??

I would really appreciate any help from you guys.
