### ISSUE TITLE
estimation speed

### ISSUE THREAD

**Issue by JulesDoe** [zju3dv/mvpose#9]
Thanks for your great work!
I have questions regarding the evaluation speed of each step. 
How long does the used feature extractor and especially the hypothesis generator take for the calculation?
How does the calculation duration scale with the number of people in the picture?
Which hardware was used? 
Thanks in advance!

**Comment by DongJT1996** [comment]
Hello, about running time and hardware, you can refer to section 4.5 of our paper. 
Does 'hypothesis generator' mean the triangulation of 2D joints? We don't test the time of it separately, which is paralleled thus it can be calculated fastly.
The time complexity of the matching algorithm is O(n^2), which can be accelerated by other multi-image matching algorithms. But I think that our algorithm is able to deal with the normal setting since the size of affinity matrix is **a*****b**, where a is the number of cameras and b is the number of people in the setting. The part of 3D pictorial structure inference is **b** times than one person since the state space to infer does not change after our matching algorithm.

**Comment by JulesDoe** [comment]
Whoops, i misclick and ended up in the wrong repo. Sorry for borthereing you and thanks for your detailed explanation both in the paper and here. :)
